name = "netdrv"
main = "src/worker.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# 前端靜態文件配置 (必須有這段，否則網頁打不開)
[site]
bucket = "./public"

# KV 配置
[[kv_namespaces]]
binding = "CONFIG_KV"
id = "baff4384e03342e599638f826b563940"

# D1 數據庫配置
[[d1_databases]]
binding = "DB"
database_name = "netfile-db"
database_id = "1f21da5d-46b1-4232-bf44-4689b7417467"
